### ISSUE TITLE
Stop Lazy Loading CSS file

### ISSUE THREAD

**Issue by dordnung** [Raruto/leaflet-ui#10]
Why is the **leaflet-ui.css** lazy loaded in any case? There is not even the possibility to disable this, because in the **default_options** the attribute **plugins** is an array and therefore **deepMerge** can not take over the own options, because it only supports objects.

**Comment by Raruto** [comment]
Just a fast fix (version **0.5.2**):

https://github.com/Raruto/leaflet-ui/blob/7b14ff66134826fbdebc6037239fb4d404a6a9dd/src/leaflet-ui.js#L486-L488

_Raruto_
