### ISSUE TITLE
missing locales/pl-PL.js file

### ISSUE THREAD

**Issue by piotrburda** [Raruto/leaflet-ui#20]
leaflet-ui is looking for non existing polish locale file

```
unpkg.com/leaflet-ui@0.6.0/dist/locales/pl-PL.js
```

but the right name of file is `pl.js`

how to fix?

**Comment by Raruto** [comment]
Hi Piotr,

> how to fix?

- https://github.com/Raruto/leaflet-gesture-handling/issues/20#issuecomment-1177141141
- https://github.com/Raruto/leaflet-ui/issues/11#issuecomment-1119595764

As already mentioned, anyone who can code a **simpler algorithm** that doesn't generate such a warning is welcome.

👋 Raruto
