### ISSUE TITLE
How to add custom leaflet layers?

### ISSUE THREAD

**Issue by haldo98** [Raruto/leaflet-ui#21]
Hi Raruto....

I am trying to implement this leaflet-ui in my project....

I want to use the regular layer function and not the one within this plugin

How do I achieve this?

**Comment by Raruto** [comment]
Roughly, I think these are the available possibilities:

## 1. https://leafletjs.com/reference#map-layers
```js
const map = L.map('id', { layers: [...] });
```

## 2. [leaflet-ui.js#L525 (v0.6.0)](https://github.com/Raruto/leaflet-ui/blob/31b300a69f0ae70b1d0c767686ca1c25c541f03a/src/leaflet-ui.js#L525)

```js

// in case you have to wait for external plugins to download
map.on('plugins_loaded', function(e) {
  L.tileLayer(...).addTo(map);
  L.geoJSON(...).addTo(map);
  L.marker(...).addTo(map);
})
```

Search also for the [`fire`](https://github.com/search?q=repo%3ARaruto%2Fleaflet-ui%20fire&type=code) function within that file for other available listeners

## 3. Custom MapType provider

see: https://github.com/Raruto/leaflet-ui/issues/1#issuecomment-538546557
