### ISSUE TITLE
This UI is easy to implement with a lot of options to customize

### ISSUE THREAD

**Issue by JCanchor** [Raruto/leaflet-ui#3]
Thanks Raruto for [suggesting](https://github.com/Raruto/leaflet-gesture-handling/issues/1) this project.

It expands the number of options we can implement as developers for our maps, and makes the experience user friendly for our visitors!

I also tested this with Leaflet 1.6.0 and it worked for the mapping functions I am using.

An FYI to others... if you want to implement custom icons, markers or other map functions, place them before the last line that starts with:  `map.once(`

**Comment by Raruto** [comment]
Thanks Jim for testing it,
if you want to have more control over the default options you can start looking [here](https://github.com/Raruto/leaflet-ui/blob/da1ec611e3d01afd6885e629a22fc1d430fce246/src/leaflet-ui.js#L69) (the map accepts mixed values in addition to the usual "true / false" options).

_Have a nice day,
Raruto_
