### ISSUE TITLE
Default options 

### ISSUE THREAD

**Issue by jlsogorb** [Raruto/leaflet-ui#5]
Hi, your code is great and very useful.
I have a question. If you need to use an apikey in a mapType (for instance:

```js
atlas: {
  name: 'Atlas',
  url: 'https://{s}.tile.thunderforest.com/mobile-atlas/{z}/{x}/{y}.png',
  options: {
    maxZoom: 24,
    ....
    // apikey: '<your apikey>',
}
```

How do you tell it into the code?
Thank you.

**Comment by Raruto** [comment]
Hi jlsogorb,

take a look at this other thread: https://github.com/Raruto/leaflet-ui/issues/1#issuecomment-538546557

_Have a nice day,
Raruto_

**Comment by jlsogorb** [comment]
That's it!!
Thank you, very much, ang great job!

**Comment by jlsogorb** [comment]
Another question. I'm using also the Leaflet Elevation code. How could I customize the summary (for instance translate the texts: "Total Length" ---> "Distancia Total" ...

**Comment by Raruto** [comment]
> Another question. I'm using also the Leaflet Elevation code. How could I customize the summary (for instance translate the texts: "Total Length" ---> "Distancia Total" ...

See [leaflet-elevation_i18n-strings.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_i18n-strings.html) and please try to ask questions in [relevant places](https://github.com/Raruto/leaflet-elevation/issues)

**Comment by jlsogorb** [comment]
Ok, thank you, and sorry.
